- packages/stream_video/README.md
- packages/stream_video_flutter/README.md
> Update image ref

- packages/stream_video/CHANGELOG.md
- packages/stream_video/README.md
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/README.md
- packages/stream_video_flutter/pubspec.yaml
> Release 0.0.1+1: changed README and update version

- packages/stream_video/lib/composed_version.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_ws_open_api.dart
- packages/stream_video/lib/src/sfu/sfu_client_impl.dart
- packages/stream_video/lib/src/sfu/ws/sfu_ws.dart
- packages/stream_video/lib/version.g.dart
Closes: https://github.com/GetStream/stream-flutter-planning/issues/12
> [12] Send client version in every request

- .github/workflows/vale-doc-lint.yml
- .styles/Vocab/Base/accept.txt
- docusaurus/docs/Flutter/01-setup/01-introduction.mdx
- docusaurus/docs/Flutter/01-setup/02-installation.mdx
- docusaurus/docs/Flutter/02-tutorials/01-audio-room.mdx
- docusaurus/docs/Flutter/03-core-concepts/02-joining-and-creating-calls.mdx
- docusaurus/docs/Flutter/03-core-concepts/03-call-state.mdx
- docusaurus/docs/Flutter/03-core-concepts/04-camera-and-microphone.mdx
- docusaurus/docs/Flutter/03-core-concepts/07-permission-and-moderation.mdx
- docusaurus/docs/Flutter/03-ui/01-overview.mdx
- docusaurus/docs/Flutter/03-ui/02-call-container.mdx
- docusaurus/docs/Flutter/06-ui-cookbook/01-overview.mdx
We have `vale` configured to catch linting errors in our documentation.
The action has been failing due to errors and these are fixed in this PR.
> docs: fix vale linting errors

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/lib/src/call_participants/call_participant.dart
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/pubspec.yaml
Release 0.0.2 
* New backend spec
* Support for reactions
> release: 0.0.2

- dogfooding/lib/repos/app_repository.dart
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/lib/stream_video_push_notification.dart
- packages/stream_video_push_notification/pubspec.yaml
Adds Firebase and APNS push provider name config
> adds provider name configuration for Firebase and APNS

- packages/stream_video_flutter/lib/src/renderer/video_renderer.dart
> fix: video track issue

- .github/workflows/legacy_version_analyze.yml
- dogfooding/pubspec.yaml
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_flutter_background/background_example/pubspec.yaml
- packages/stream_video_flutter_background/pubspec.yaml
- packages/stream_video_push_notification/pubspec.yaml
Updated the min SDK version required to Flutter 3.7/Dart 2.19.
Also updated all the dependencies to the resolvable version.
> chore(repo): update minimum supported SDK version to Flutter 3.7/Dart 2.19

- docusaurus/docs/Flutter/02-tutorials/03-livestreaming.mdx
- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/permissions/permissions_manager.dart
- packages/stream_video/lib/src/call/state/mixins/state_call_actions_mixin.dart
- packages/stream_video/lib/src/call/state/mixins/state_lifecycle_mixin.dart
- packages/stream_video/lib/src/call_state.dart
- packages/stream_video/lib/src/coordinator/coordinator_client.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart
- packages/stream_video/lib/src/coordinator/open_api/open_api_extensions.dart
- packages/stream_video/lib/src/coordinator/retry/coordinator_client_retry.dart
- packages/stream_video/lib/src/models/call_egress.dart
- packages/stream_video/lib/src/models/call_metadata.dart
- packages/stream_video/lib/src/models/models.dart
- packages/stream_video_push_notification/test/stream_video_push_notification_test.dart
Closes: https://stream-io.atlassian.net/browse/FVS-49
Related thread: https://getstream.slack.com/archives/C022N8JNQGZ/p1691695904421399
> Expose egress, rename broadcasting to HLS

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/version.g.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/example/lib/proxy/proxy.dart
- packages/stream_video_flutter/example/lib/screen/home_tabs/call_text_field.dart
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/lib/src/call_controls/controls/leave_call_option.dart
- packages/stream_video_flutter/lib/src/call_controls/controls/toggle_recording_option.dart
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_flutter_background/CHANGELOG.md
- packages/stream_video_flutter_background/lib/model/notification_options.dart
- packages/stream_video_flutter_background/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/lib/stream_video_push_notification.dart
- packages/stream_video_push_notification/pubspec.yaml
Reverts GetStream/stream-video-flutter#468
> Revert "chore: prepare for new release."

- packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_ws_open_api.dart
Closes: [FVS-79](https://stream-io.atlassian.net/browse/FVS-79)
[FVS-79]: https://stream-io.atlassian.net/browse/FVS-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FVS-79] pass connection_id in every request

- docusaurus/docs/Flutter/01-setup/03-quickstart.mdx
- docusaurus/docs/Flutter/02-tutorials/01-video-calling.mdx
- docusaurus/docs/Flutter/02-tutorials/02-audio-room.mdx
- docusaurus/docs/Flutter/02-tutorials/03-livestreaming.mdx
- docusaurus/docs/Flutter/03-core-concepts/02-joining-and-creating-calls.mdx
- docusaurus/docs/Flutter/04-ui/04-call-content.mdx
- docusaurus/docs/Flutter/04-ui/05-call-controls.mdx
- docusaurus/docs/Flutter/05-advanced/01-deeplinking.mdx
- docusaurus/docs/Flutter/06-ui-cookbook/02-participant-list.mdx
- docusaurus/docs/Flutter/06-ui-cookbook/14-chat-with-video.mdx
- dogfooding/lib/main.dart
- dogfooding/lib/src/screens/call_screen.dart
- dogfooding/lib/src/screens/home_screen.dart
- packages/stream_video/lib/src/action/internal/lifecycle_action.dart
- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/state/mixins/state_lifecycle_mixin.dart
- packages/stream_video/lib/src/coordinator/coordinator_client.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart
- packages/stream_video/lib/src/coordinator/retry/coordinator_client_retry.dart
- packages/stream_video/lib/src/models/call_received_data.dart
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video_flutter/example/lib/screen/home_tabs/start_call_tab.dart
- packages/stream_video_flutter/lib/src/call_background/background_service.dart
- packages/stream_video_flutter/lib/src/call_controls/controls/leave_call_option.dart
- packages/stream_video_flutter/lib/src/call_screen/call_container.dart
- packages/stream_video_flutter/lib/src/call_screen/incoming_call/incoming_call_content.dart
- packages/stream_video_flutter/lib/src/call_screen/lobby_view.dart
- packages/stream_video_flutter/lib/src/call_screen/outgoing_call/outgoing_call_content.dart
Closes: https://stream-io.atlassian.net/browse/FVS-81
- `connect` was renamed to `join` => :rotating_light: breaking change
- `disconnect` was renamed to `leave` => :rotating_light: breaking change
- added `call.get()` - new request available on BE
- `LobbyView` - now uses `call.get` & listens participants events to display list of members
> [FVS-81] lobby logic changes & call api alignment

- packages/stream_video/lib/src/coordinator/models/coordinator_events.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart
- packages/stream_video/lib/src/coordinator/open_api/open_api_extensions.dart
- packages/stream_video/lib/src/coordinator/open_api/open_api_mapper_extensions.dart
- packages/stream_video/lib/src/models/call_metadata.dart
- packages/stream_video/lib/src/models/call_session_data.dart
- packages/stream_video/lib/src/models/models.dart
- packages/stream_video_flutter/lib/src/call_screen/lobby_participants_view.dart
- packages/stream_video_flutter/lib/src/call_screen/lobby_view.dart
- packages/stream_video_flutter/lib/src/theme/lobby_view_theme.dart
Closes: https://stream-io.atlassian.net/browse/FVS-81
> [FVS-82] Display call participants on Lobby View

- README.md
- development.md
Related to: [notion page](https://www.notion.so/stream-wiki/Flutter-Milestones-8763cb5e30a24d77b8003d2ac6132c54)
> add milestones to README.md

- dogfooding/lib/app/app_content.dart
Fixes incoming bug for CallKit
> Callkit incoming fix

- dogfooding/lib/di/injector.dart
- packages/stream_video/lib/open_api/video/coordinator/api_helper.dart
- packages/stream_video/lib/open_api/video/coordinator/model/call_session_response.dart
- packages/stream_video/lib/src/call/state/call_state_notifier.dart
- packages/stream_video/lib/src/call/state/mixins/state_sfu_mixin.dart
Fix several issues
- duplicate participant
- dateTime parsing
- reset StreamVideo on unregister
> FVS-84: fix duplicate participant, dateTime parsing, reset StreamVideo on unregister

- docusaurus/docs/Flutter/01-setup/03-quickstart.mdx
- docusaurus/docs/Flutter/02-tutorials/01-video-calling.mdx
- docusaurus/docs/Flutter/03-core-concepts/01-authentication.mdx
> FVS-84: update docs (except sample apps)

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/version.g.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_flutter_background/CHANGELOG.md
- packages/stream_video_flutter_background/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/pubspec.yaml
* fix(ci): fix workflows. by @xsahil03x in https://github.com/GetStream/stream-video-flutter/pull/473
* Ringing guide by @deven98 in https://github.com/GetStream/stream-video-flutter/pull/474
* [FVS-79] pass connection_id in every request by @kanat in https://github.com/GetStream/stream-video-flutter/pull/475
* [FVS-81] lobby logic changes & call api alignment by @kanat in https://github.com/GetStream/stream-video-flutter/pull/480
* [FVS-82] Display call participants on Lobby View by @kanat in https://github.com/GetStream/stream-video-flutter/pull/479
* Hide debug stats in production by @Nash0x7E2 in https://github.com/GetStream/stream-video-flutter/pull/481
* UI Cookbook Guides by @Nash0x7E2 in https://github.com/GetStream/stream-video-flutter/pull/482
* docs: added call participants ui …
> Release: v0.1.0

- docusaurus/docs/Flutter/05-advanced/02-ringing.mdx
- dogfooding/lib/app/app_content.dart
Modified ringing docs for new version
> docs: Ringing doc fix

- dogfooding/lib/app/app_content.dart
- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/core/client_state.dart
- packages/stream_video/lib/src/push_notification/call_kit_events.dart
- packages/stream_video/lib/src/push_notification/push_notification_manager.dart
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
Related thread:
https://getstream.slack.com/archives/C04EZ12CNLE/p1695984097377889
> Do not join active call

- packages/stream_video/lib/src/stream_video.dart
> Anonymous users should not connect to the WS

- packages/stream_video/lib/src/core/client_state.dart
> fix typo from #499

- packages/stream_video_flutter/lib/src/call_controls/call_controls.dart
- packages/stream_video_flutter/lib/src/call_screen/call_content/call_content.dart
Fixes missing call controls in landscape mode
> fix: call controls in landscape

- packages/stream_video/lib/open_api/video/coordinator/model/user_response.dart
- packages/stream_video/lib/src/models/call_metadata.dart
- packages/stream_video/lib/src/models/guest_created_data.dart
Closes: https://stream-io.atlassian.net/browse/FVS-88
> [FVS-88] unable to join a call

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/version.g.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_flutter_background/CHANGELOG.md
- packages/stream_video_flutter_background/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/pubspec.yaml
> release: v0.1.1

- README.md
> docs: updated roadmap

- README.md
- development.md
> doc(repo): update roadmap

- development.md
Fixed roadmap to align with other SDKs and ensuring parity.
> docs: Fixed roadmap

- development.md
- docusaurus/docs/Flutter/05-advanced/02-ringing.mdx
- packages/stream_video_flutter/lib/src/call_screen/call_container.dart
- packages/stream_video_flutter/lib/src/call_screen/incoming_call/incoming_call_content.dart
- packages/stream_video_flutter/lib/src/call_screen/outgoing_call/outgoing_call_content.dart
- packages/stream_video_push_notification/.metadata
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/ios/Classes/StreamVideoPKDelegateManager.swift
- packages/stream_video_push_notification/ios/Classes/StreamVideoPushNotificationPlugin.swift
- packages/stream_video_push_notification/ios/Classes/StreamVideoPushParams.swift
- packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
- packages/stream_video_push_notification/lib/src/stream_video_push_params.dart
- packages/stream_video_push_notification/lib/src/stream_video_push_params.g.dart
- packages/stream_video_push_notification/lib/stream_video_push_notification_method_channel.dart
- packages/stream_video_push_notification/lib/stream_video_push_notification_platform_interface.dart
- packages/stream_video_push_notification/pubspec.yaml
Added builders for incoming/outgoing call screens to customize participants and avatars.
Added incoming display name override for CallKit
Fixed missing app icon in CallKit call screen
> feat: Added customization of incoming/outgoing call screen

- .styles/Vocab/Base/accept.txt
- docusaurus/docs/Flutter/02-tutorials/03-livestreaming.mdx
- docusaurus/docs/Flutter/03-core-concepts/02-joining-and-creating-calls.mdx
- docusaurus/docs/Flutter/05-advanced/02-ringing.mdx
- docusaurus/docs/Flutter/06-ui-cookbook/05-watching-a-livestream.mdx
Fixes vale documentation checks
> fix: vale doc fixes

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/version.g.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_flutter_background/CHANGELOG.md
- packages/stream_video_flutter_background/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/pubspec.yaml
Release PR for v0.2.0 of the Flutter SDK.
> release: v0.2.0

- packages/stream_video_flutter/lib/src/call_screen/call_content/call_content.dart
- packages/stream_video_flutter/lib/src/livestream/livestream_info.dart
- packages/stream_video_flutter/lib/src/livestream/livestream_toggle.dart
- packages/stream_video_flutter/lib/src/theme/call_content_theme.dart
- packages/stream_video_flutter/lib/src/theme/stream_color_theme.dart
- packages/stream_video_flutter/lib/src/theme/stream_video_theme.dart
- packages/stream_video_flutter/lib/src/theme/themes.dart
> Added `StreamCallContentTheme` and fixes for other themes

- dogfooding/macos/Podfile
- dogfooding/macos/Runner.xcodeproj/project.pbxproj
> fix: macOS build

- packages/stream_video/lib/open_api/video/coordinator/model/record_settings.dart
> fix: fixes `queryCalls` null check issue

- packages/stream_video/lib/src/call/session/call_session.dart
- packages/stream_video/lib/src/webrtc/rtc_manager.dart
> fix: added apple audio configuration to make audio work in silent mode

- packages/stream_video/lib/src/utils/subscriptions.dart
- packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
Added automatic call cancelation of ringing call when caller is ending the call.
> feat: ringing call cancelation

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/version.g.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/pubspec.yaml
v0.3 release for all Flutter Video SDKs
> release: v0.3

- .github/workflows/legacy_version_analyze.yml
> chore(repo): upgrade pipeline flutter version

- packages/stream_video_flutter/example/lib/core/token_service.dart
- packages/stream_video_flutter/example/lib/main.dart
Relates to:
- https://github.com/GetStream/stream-video-flutter/pull/527
> chore: fetch token based on environment

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/version.g.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/lib/src/call_controls/controls/add_reaction_option.dart
- packages/stream_video_flutter/lib/src/livestream/livestream_player.dart
- packages/stream_video_flutter/lib/src/livestream/livestream_toggle.dart
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/pubspec.yaml
> release: 0.3.1

- dogfooding/android/app/src/main/AndroidManifest.xml
- packages/stream_video_flutter/example/android/app/src/main/AndroidManifest.xml
Was: 
- when tapping on notification => nothing happens
Now:
- when tapping on notification => call screen opens
> (fix) notification tap does nothing

- dogfooding/android/app/build.gradle
- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/session/call_session.dart
- packages/stream_video/lib/src/models/call_status.dart
- packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/StreamVideoFlutterPlugin.kt
- packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/service/notification/NotificationActionReceiver.kt
- packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/service/utils/AndroidUtils.kt
- packages/stream_video_flutter/lib/src/call_screen/call_content/call_content.dart
> fix: fix for Android SDK versions <26

- docusaurus/docs/Flutter/01-setup/01-introduction.mdx
This PR updates the introduction page of our Docs to include an overview of the product and links back to the three main tutorials on the website
> Update documentation intro page

- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/call_ringing_state.dart
- packages/stream_video/lib/src/push_notification/push_notification_manager.dart
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video/lib/stream_video.dart
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
- Fixes late push notification handling on Android, where already ended call was ringing if the device was offline and the push was delivered with a delay
- Call is also now ending correctly when caller times out while calling
> feat: push notification enhancements

- dogfooding/pubspec.yaml
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/version.g.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_push_notification/CHANGELOG.md
- packages/stream_video_push_notification/pubspec.yaml
v0.3.2 Release of the Video SDK
> release: v0.3.2

- dogfooding/android/app/src/main/AndroidManifest.xml
- dogfooding/ios/Runner/Runner.entitlements
- dogfooding/lib/app/app_content.dart
- dogfooding/lib/core/repos/token_service.dart
- dogfooding/lib/screens/home_screen.dart
- dogfooding/lib/screens/login_screen.dart
- packages/stream_video/lib/src/core/client_state.dart
- packages/stream_video/lib/src/webrtc/model/stats/rtc_stats_mapper.dart
- packages/stream_video_flutter/lib/src/call_participants/regular_call_participants_content.dart
Environment switcher on login screen + dynamic link support for all environments. 
https://github.com/GetStream/stream-video-flutter/assets/5622717/6f16d23e-44b3-4f74-bad5-91a53be8f8d7
> feat(dogfooding): env switcher + dynamic link support

- dogfooding/lib/app/app.dart
- dogfooding/lib/app/app_content.dart
- dogfooding/lib/app/user_auth_controller.dart
- dogfooding/lib/core/repos/app_preferences.dart
- dogfooding/lib/core/repos/token_service.dart
- dogfooding/lib/core/repos/user_chat_repository.dart
- dogfooding/lib/di/injector.dart
- dogfooding/lib/screens/call_screen.dart
- dogfooding/lib/screens/home_screen.dart
- dogfooding/lib/screens/login_screen.dart
- dogfooding/lib/screens/stats_latency_chart.dart
- dogfooding/lib/widgets/environment_switcher.dart
- Fixes environment handling in Dogfooding
- Disables back gestures on the call screen
- Fixes the latency chart axis labels
> fix: dogfooding env handling

- .github/workflows/app-distribute.yml
As described [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
> chore(repo): distribute dogfooding only when there are changes to it

- .gitignore
Ignore files associated with Flutter Version Manager.
> Ignore .fvm

- packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/service/notification/StreamNotificationBuilderImpl.kt
Silenced Android notifications
> fix: silenced android notifications

- docusaurus/docs/Flutter/05-advanced/05-call-recording.mdx
This PR adds documentation for using the call recording options in the Flutter SDK.
> Add docs for Call Recording 

- packages/stream_video/lib/src/call/state/mixins/state_lifecycle_mixin.dart
Chooses first device if audio output is null
> fix: audio output default device

- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/pubspec.yaml
reversing flutter_webrtc version bump that caused compilation issues for Flutter 3.19
> fix: fixing compilation issues in Flutter 3.19 

- docusaurus/docs/Flutter/03-core-concepts/01-authentication.mdx
- docusaurus/docs/Flutter/03-core-concepts/03-call-state.mdx
- docusaurus/docs/Flutter/03-core-concepts/04-camera-and-microphone.mdx
- docusaurus/docs/Flutter/03-core-concepts/05-call-types.mdx
- docusaurus/docs/Flutter/03-core-concepts/06-querying-calls.mdx
- docusaurus/docs/Flutter/03-core-concepts/07-permission-and-moderation.mdx
- docusaurus/docs/Flutter/04-ui/02-call-container.mdx
- docusaurus/docs/Flutter/04-ui/03-video-render.mdx
- docusaurus/docs/Flutter/04-ui/04-call-content.mdx
- docusaurus/docs/Flutter/04-ui/06-video-theme.mdx
- docusaurus/docs/Flutter/05-advanced/04-picture-in-picture.mdx
- docusaurus/docs/Flutter/06-ui-cookbook/04-chat-with-video.mdx
> docs: small changes and doc fixes

- packages/stream_video/lib/src/call/call.dart
Fixes full reconnect issue when multiple users showed up and tracks disappeared.
> fix: full reconnect flow

- docusaurus/docs/Flutter/05-advanced/02-ringing.mdx
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
_Explain how this change can be tested (or why it can't be tested)_
_Provide a patch below if it is necessary for testing_
<details>
<summary>Provide the patch summary here</summary>
```
Provide the patch code here
```
</details>
> Update the push notifications docs

- packages/stream_video_flutter/lib/stream_video_flutter.dart
Solves https://github.com/GetStream/stream-video-flutter/issues/711
> fix: export floating view alignment enum

- docusaurus/docs/Flutter/05-advanced/05-call-recording.mdx
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video_flutter/CHANGELOG.md
Solves https://github.com/GetStream/stream-video-flutter/issues/706
> chore(llc): added listRecordings method to StreamVideo class

- packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/service/notification/StreamNotificationBuilderImpl.kt
Setting a lockscreen visibility for a call ringing notrification to public.
> fix: setting lockscreen visibility to public

- docusaurus/docs/Flutter/03-core-concepts/01-authentication.mdx
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
_Explain how this change can be tested (or why it can't be tested)_
_Provide a patch below if it is necessary for testing_
<details>
<summary>Provide the patch summary here</summary>
```
Provide the patch code here
```
</details>
> Added more details about the anon users

- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/call_connect_options.dart
- packages/stream_video/lib/src/models/call_settings.dart
Support the target resolution setting configured on the dashboard for both camera and screen sharing.
> feat(llc): support target resolution setting

- README.md
> docs: adds packages size badges to Readme

- dogfooding/lib/app/app_content.dart
- dogfooding/lib/screens/home_screen.dart
- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/session/dynascale_manager.dart
- packages/stream_video/lib/src/coordinator/coordinator_client.dart
- packages/stream_video/lib/src/coordinator/models/coordinator_events.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart
- packages/stream_video/lib/src/coordinator/open_api/open_api_extensions.dart
- packages/stream_video/lib/src/coordinator/open_api/open_api_mapper_extensions.dart
- packages/stream_video/lib/src/coordinator/retry/coordinator_client_retry.dart
- packages/stream_video/lib/src/models/call_settings.dart
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video_flutter/lib/src/call_screen/call_content/picture_in_picture/stream_picture_in_picture_ui_kit_view.dart
- packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
- Fixes for various ringing issues
- Added geofencing and broadcasting settings to call getOrCreate/update
- Fix for ending PiP on iOS when call disconnects
> fix(llc): Fixes for various small ringing issues

- dogfooding/lib/app/app_content.dart
- dogfooding/lib/di/injector.dart
- dogfooding/lib/screens/home_screen.dart
- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/src/call/sfu_stats_reporter.dart
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_push_notification/ios/Classes/StreamVideoPKDelegateManager.swift
- packages/stream_video_push_notification/ios/Classes/StreamVideoPushNotificationPlugin.swift
- packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
- packages/stream_video_push_notification/lib/stream_video_push_notification_method_channel.dart
- packages/stream_video_push_notification/lib/stream_video_push_notification_platform_interface.dart
This pull request includes several changes to enhance the handling of call events and simplify the implementation of the ringing flow in the `StreamVideo` package. The most important changes include the introduction of new methods to manage call events, the deprecation of the `backgroundVoipCallHandler` parameter, and updates to the documentation.
> chore: ringing cleanup

- .github/workflows/app-distribute.yml
- .github/workflows/legacy_version_analyze.yml
- .github/workflows/stream_video_flutter_workflow.yml
- dogfooding/linux/flutter/generated_plugin_registrant.cc
- dogfooding/linux/flutter/generated_plugins.cmake
- dogfooding/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- dogfooding/pubspec.yaml
- dogfooding/windows/flutter/generated_plugins.cmake
- melos.yaml
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/example/android/app/build.gradle
- packages/stream_video_flutter/example/android/app/proguard-rules.pro
- packages/stream_video_flutter/example/android/build.gradle
- packages/stream_video_flutter/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/stream_video_flutter/example/android/settings.gradle
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/example/windows/flutter/generated_plugins.cmake
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_push_notification/pubspec.yaml
- packages/stream_video_screen_sharing/pubspec.yaml
- pubspec.lock
- pubspec.yaml
Also updates flutter_webrtc dependency
Compatibility with Flutter 3.29
This updates webrtc version with fixes for the android plugin system. It also raises the minimum flutter version to previous stable.
No UI changes
I ran the dogfooding app on Android
> chore Update minimal flutter version

- dogfooding/lib/di/injector.dart
- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/state/mixins/state_participant_mixin.dart
- packages/stream_video/lib/src/call_state.dart
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video/lib/src/webrtc/rtc_track/rtc_local_track.dart
- packages/stream_video/pubspec.yaml
- packages/stream_video_flutter/CHANGELOG.md
- packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/service/PictureInPictureHelper.kt
- packages/stream_video_flutter/example/pubspec.yaml
- packages/stream_video_flutter/lib/src/call_participants/call_participants.dart
- packages/stream_video_flutter/lib/src/call_screen/call_content/call_content.dart
- packages/stream_video_flutter/lib/src/call_screen/call_content/picture_in_picture/picture_in_picture_configuration.dart
- packages/stream_video_flutter/lib/src/call_screen/call_content/picture_in_picture/stream_picture_in_picture_ui_kit_view.dart
- packages/stream_video_flutter/pubspec.yaml
- packages/stream_video_push_notification/lib/stream_video_push_notification_method_channel.dart
- packages/stream_video_push_notification/pubspec.yaml
This pull request includes several changes to improve the functionality and user experience of the video calling feature, particularly focusing on multitasking and Picture-in-Picture (PiP) support. The most important changes include modifications to enable multitasking camera access on iOS, updates to PiP configurations, and adjustments to the app's behavior when in the background.
* Added a method to enable iOS multitasking camera access and updated the `CallState` class to include a flag for this feature. (`packages/stream_video/lib/src/call/call.dart`, `packages/stream_video/lib/src/call_state.dart`) [[1]](diffhunk://#diff-906f4e1b5915f3d7ca284e5ad50865c5e265029e2cf4c804de44e8e8f4d6695eR1983-R1992) [[2]](diffhunk://#diff-906f4e1b5915f3d7ca284e5ad50865c5e265029e2cf4c804de44e8e8f4d6695eL2 …
> fix: Picture in Picture improvements

- dogfooding/README.md
- dogfooding/android/gradle.properties
- packages/stream_video_flutter/example/android/app/build.gradle
- packages/stream_video_flutter/example/android/gradle.properties
- packages/stream_video_flutter/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/stream_video_flutter/example/pubspec.yaml
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
_Explain how this change can be tested (or why it can't be tested)_
_Provide a patch below if it is necessary for testing_
<details>
<summary>Provide the patch summary here</summary>
```
Provide the patch code here
```
</details>
> chore: update dogfooding readme, fix android build

- .github/workflows/app-distribute.yml
- dogfooding/lib/utils/consts.dart
This makes sure we can also deploy the web app to github pages.
It's now running on https://getstream.github.io/stream-video-flutter/
> feat: deploy flutter web

- packages/stream_video/CHANGELOG.md
- packages/stream_video/lib/src/call/call.dart
Closes FLU-93
This PR adds camera focus and zoom control features to the SDK, allowing users to:
- Adjust the camera zoom level with Call.setZoom()
- Control focus and exposure points with Call.focus()
> feat(llc): camera zoom and focus

- dogfooding/lib/di/injector.dart
- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/coordinator/open_api/coordinator_ws.dart
- packages/stream_video/lib/src/sfu/sfu_client.dart
- packages/stream_video/lib/src/sfu/ws/sfu_ws.dart
- packages/stream_video/lib/src/stream_video.dart
- packages/stream_video/lib/src/webrtc/peer_connection.dart
The verbose logging became so excessive that it's difficult to extract anything meaningful from it. This PR establishes the default logging for dogfooding at the debug level and adjusts some logging levels to enhance the informativeness of the debug output.
> chore: cleanup logging

- packages/stream_video/lib/src/call/call.dart
- packages/stream_video/lib/src/call/call_events.dart
- packages/stream_video/lib/src/coordinator/models/coordinator_events.dart
- packages/stream_video/lib/src/coordinator/open_api/open_api_mapper_extensions.dart
Added handling for missing coordinator events.
> chore: handle all coord events

- .github/workflows/stream_video_flutter_workflow.yml
- dogfooding/ios/Podfile
- dogfooding/ios/Runner.xcodeproj/project.pbxproj
- dogfooding/lib/core/repos/token_service.dart
- dogfooding/lib/screens/home_screen.dart
- dogfooding/lib/screens/qr_code_scanner.dart
- dogfooding/pubspec.yaml
Allow for qr code scanning to join a call
This scans the code and if it's a valid join url it will parse it and enter the code in the text field. If the environment is wrong and you are able to switch environments (!kIsProd) you will get a dialog to logout. If it's not a valid URL or you cannot switch nothing happens.
https://github.com/user-attachments/assets/489311ab-09b2-4c0d-88e2-50f2e37ee7fb
I've tested it on an Android phone and iPad.
This only works on mobile devices, so best to test on a real device.
> feat: qr scanner on dogfooding app

- dogfooding/lib/app/app.dart
- dogfooding/lib/app/app_content.dart
- dogfooding/lib/app/user_auth_controller.dart
- dogfooding/lib/core/model/environment.dart
- dogfooding/lib/core/repos/app_preferences.dart
- dogfooding/lib/core/repos/token_service.dart
- dogfooding/lib/core/repos/user_chat_repository.dart
- dogfooding/lib/di/injector.dart
- dogfooding/lib/screens/call_participants_list.dart
- dogfooding/lib/screens/call_screen.dart
- dogfooding/lib/screens/home_screen.dart
- dogfooding/lib/screens/login_screen.dart
- dogfooding/lib/widgets/environment_switcher.dart
- dogfooding/lib/widgets/share_call_card.dart
- dogfooding/macos/Runner.xcodeproj/project.pbxproj
- dogfooding/pubspec.yaml
fixes FLU-101
We want to show a QR code so people can join the call more easily from another device.
This adds a QR code with the full url and also changes the share URL button to actually share the URL instead of the call ID. The button to copy the call id is made a bit nicer.
| --- | --- |
| <img width="856" alt="image" src="https://github.com/user-attachments/assets/1efca49f-86b7-4f4d-bb7a-dccb0ab8796b" /> | <img width="900" alt="image" src="https://github.com/user-attachments/assets/dc1fced3-a844-413f-9101-dc5bf7fc211c" /> <img width="856" alt="image" src="https://github.com/user-attachments/assets/c03e48a2-aea1-4f3f-a827-764d6f935d77" /> |
| <img width="900" alt="image" src="https://github.com/user-attachments/assets/6a7873af-e455-4efa-b7dc-765288a63b18" /> | <img …
> dogfooding: show call qr code

- dogfooding/pubspec.yaml
- melos.yaml
- packages/stream_video_flutter/example/pubspec.yaml
Update share_plus package in dogfooding and example to be compatible with latest chat release.
> update share_plus package in examples

- .github/actions/package_analysis/action.yml
- .github/workflows/beta_version_analyze.yml
- .github/workflows/legacy_version_analyze.yml
- .github/workflows/pr_title.yml
- .github/workflows/stale_issue_checker.yml
- .github/workflows/stream_video_flutter_workflow.yml
Get workflows more aligned with chat repository
* legacy version analysis now also runs tests (excluding goldens)
* beta version analysis runs analysis and tests once a week and posts failures to slack
* PR title makes sure the title of the PR includes the adapted libraries and has updates in changelogs.
* Stale issue tracker helps us to close inactive tickets.
> chore(repo): workflow updates

- .github/workflows/pr_title.yml
Workflow should run when targeting main, we don't have a master here.
> chore(repo): fix PR title workflow
