GetStream/stream-video-flutter

packages/stream_video_flutter/lib/src/call_screen/call_content/call_content.dart
This PR tweaks the debug stats visibility to ensure stats are only shown when the app is in debug mode.
=> Hide debug stats in production

docusaurus/docs/Flutter/05-advanced/01-deeplinking.mdx
=> docs: fixed deeplink docs

packages/stream_video/lib/open_api/video/coordinator/model/call_updated_event.dart, packages/stream_video/lib/src/coordinator/open_api/open_api_mapper_extensions.dart
Previously, any update event would lead to a cast issue leading to `capabilities_by_role` not being cast correctly. This PR fixes that issue and update events no longer cause an error.
=> fix: fixes cast issue for `capabilities_by_role` in `CoordinatorCallUpdatedEvent`

docusaurus/docs/Flutter/03-core-concepts/01-authentication.mdx, packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/coordinator/coordinator_client.dart, packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart, packages/stream_video/lib/src/coordinator/open_api/coordinator_ws_open_api.dart, packages/stream_video/lib/src/coordinator/retry/coordinator_client_retry.dart, packages/stream_video/lib/src/stream_video.dart
Adds a `includeUserDetails` field to determine if user should be passed to backend.
By default, both `connectUser` and auto-connecting default to passing fields to backend.
=> fix: `connectUser` / auto connect bug 

packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/coordinator/coordinator_client.dart, packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart, packages/stream_video/lib/src/coordinator/retry/coordinator_client_retry.dart
=> fix: added missing params to `getOrCreate()` 

packages/stream_video_flutter/lib/src/theme/stream_video_theme.dart
Fixes #546
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
_Explain how this change can be tested (or why it can't be tested)_
_Provide a patch below if it is necessary for testing_
<details>
<summary>Provide the patch summary here</summary>
```
Provide the patch code here
```
</details>
=> StreamVideoTheme missing callContentTheme parameter

packages/stream_video/lib/src/call/call_type.dart, packages/stream_video/lib/src/models/call_cid.dart
fixed cid comparison that was breaking event handing
=> fix: fixed cid comparison

dogfooding/lib/screens/lobby_screen.dart, packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/state/mixins/state_lifecycle_mixin.dart, packages/stream_video/lib/src/call_state.dart
Previously wherever we get a call details we updated the CallState with participants created from member list. First problem was that it was losing the state of CallParticipant which contains publishedTracks. Second is that it should iterate session participats and not members collection.
=> fix(llc): fixing call participants creation when receving call details

packages/stream_video_flutter/example/android/app/build.gradle, packages/stream_video_flutter/lib/src/call_screen/lobby_view.dart
This PR addresses the issues outlined in the ticket https://github.com/GetStream/stream-video-flutter/issues/617.
Migrates the `StreamLobbyView` view implementation to `TrackOptions.enabled` instead of `TrackOptions.provided`. The Camera and Microphone on/off state are checked and synced to a new instance of `CallConnectOptions` before being passed to the active `Call` object. 
Tested on:
- Android: Pixel 3a API version 32 
- iOS: iPhone 15 Pro Max, iOS 17.4 
- React: Stream's current production [demo app](https://getstream.io/video/demos/) 
- To be added in a separate PR (testing infra needs to be configured)
=> Migrate LobbyView to `TrackOptions.enabled`

packages/stream_video_flutter/lib/src/renderer/video_renderer.dart
---
Improve user experience by ensuring the video orientation matches user expectations. The change prevents mirroring for local back camera video streams, making the display more intuitive, especially in contexts where mirroring could confuse or degrade the viewing experience.
Modified the `StreamVideoRenderer` class to detect if a video stream is local and from the back camera. If these conditions are met, the video is not mirrored. This involved checking the `videoTrack`'s `mediaConstraints.facingMode` against `FacingMode.environment` to identify back camera usage and adjusting the `mirror` variable accordingly.
| --- | --- |
| ![Before Image](https://i.imgur.com/SmVUv7t.jpg) | ![After Image](https://i.imgur.com/08DbBh8.jpg) |
1. Test with front camera to ensure …
=> fix(video_renderer): disable mirroring for rendering local back camera stream

packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/call/call_events.dart
The current event mapper uses the call ID instead of the CID ("abcd1234" instead of "default:abcd1234") leading to errors. This PR replaces it with the CID retrieved from state.
=> fix: fixes incorrect cid value crash

packages/stream_video_flutter/lib/src/call_participants/call_participants.dart, packages/stream_video_flutter/lib/src/call_participants/regular_call_participants_content.dart, packages/stream_video_flutter/lib/src/call_participants/screen_share_call_participants_content.dart, packages/stream_video_flutter/lib/src/renderer/video_renderer.dart
Fixes screen sharing view persisting beyond stopping sharing as well as the track not showing in the view.
=> fix: fixed screensharing persistence and track issue

docusaurus/docs/Flutter/05-advanced/03-screen-sharing.mdx, packages/stream_video/lib/src/call/call.dart, packages/stream_video_flutter/lib/src/call_controls/controls/toggle_screen_sharing_option.dart
Adds permission request to `ToggleScreenShareOption` to handle requirements on Android 14 onwards.
=> fix: fixes screen sharing permission handling on Android

dogfooding/lib/screens/call_screen.dart, dogfooding/lib/screens/home_screen.dart
`call.end()` is permission based action (most likely should be invoked by a host/admin)
By default, we should `reject` and `leave`.
=> fix hang-up behaviour

packages/stream_video/lib/src/stream_video.dart, packages/stream_video_flutter/CHANGELOG.md, packages/stream_video_push_notification/CHANGELOG.md, packages/stream_video_push_notification/ios/Classes/StreamVideoPKDelegateManager.swift
CallKit now displays if the call is an audio or video call on the incoming CallKit screen.
Fixes #708
=> fix: CallKit now displays appropriate video and audio call labels.

packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/service/notification/NotificationActionUtils.kt, packages/stream_video_flutter_background/android/src/main/kotlin/io/getstream/video/flutter/background/stream_video_flutter_background/service/notification/NotificationActionUtils.kt
Since we use `RECEIVER_NOT_EXPORTED` flag while registering the `BroadcastReceiver`, we also have to set `packageName` to Intent itself to let OS know that actions are being sent internally in the app.
=> [PBE-0] fix android notification buttons being unresponsive

packages/stream_video_flutter/lib/src/call_screen/lobby_video.dart, packages/stream_video_flutter/lib/src/call_screen/lobby_view.dart
This allows the `StreamLobbyView` and `StreamLobbyVideo` to use a custom instance of `StreamVideo`.
This ensures that apps which initialize Stream using `StreamVideo.create` can still use these components.
Resolves one of the suggestions in #741 
Add an optional `streamVideo` parameters to the constructors of `StreamLobbyView` and `StreamLobbyVideo`. If this parameter is omitted, the widgets will fall back to `StreamVideo.instance`.
| --- | --- |
| img | img |
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
Pass in a non-singleton instance of …
=> Allow Lobby components to use a custom instance of StreamVideo

packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/call/call.dart, packages/stream_video/pubspec.yaml, packages/stream_video_flutter/CHANGELOG.md
Due to [license issues](https://github.com/github/dmca/blob/master/2024/09/2024-09-04-internet-connection-checker-plus.md) `internet_connection_checker` version was reverted. This PR migrates to `internet_connection_checker_plus` instead.
=> fix: migrating to internet connection checker plus

dogfooding/lib/widgets/call_duration_title.dart, packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/state/mixins/state_participant_mixin.dart, packages/stream_video/lib/src/call_state.dart, packages/stream_video/lib/src/coordinator/open_api/open_api_extensions.dart, packages/stream_video/lib/src/models/call_session_data.dart, packages/stream_video/lib/src/stream_video.dart, packages/stream_video_flutter/CHANGELOG.md
**Overview**
Handlers for the `call.session_participant_count_updated` event.
The Coordinator will occasionally deliver this event to all clients, and it will carry the most recent state of:
`anonymous_participant_count` and `participant_count_by_role`
**Implementation notes**
`watch` parameter is now added to `Call.get()` and `Call.getOrCreate()` methods. When set to `true` the coordinator events will be listened to even before joining the call.
The `CallState` is extended with `participantCount` and `anonymousParticipantCount` fields.
This values from the `call.session_participant_count_updated` event are used to update those fields but only when the call status isn't JOINED. Once the call is JOINED, these values will be populated from the SFU heart checks.
=> feat(llc): Added participants count in CallState

docusaurus/docs/Flutter/05-advanced/10-manual-video-quality-selection.mdx, docusaurus/docs/Flutter/05-advanced/11-session-timers.mdx, dogfooding/lib/widgets/settings_menu.dart, packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/session/call_session.dart, packages/stream_video/lib/src/call/session/call_session_factory.dart, packages/stream_video/lib/src/call/session/dynascale_manager.dart, packages/stream_video/lib/src/call_state.dart, packages/stream_video/lib/src/extensions/call_participant_state_ext.dart, packages/stream_video/lib/src/models/subscription_change.dart, packages/stream_video/lib/src/sfu/data/models/sfu_subscription_details.dart, packages/stream_video/lib/stream_video.dart, packages/stream_video_flutter/CHANGELOG.md, packages/stream_video_flutter/lib/src/renderer/video_renderer.dart
Adds APIs to manually override incoming video quality:
`await call.setPreferredIncomingVideoResolution(VideoResolution(width: 640, height: 480), sessionIds: [ids]);`
Specify preference for incoming video resolution. The preference will be matched as close as possible, but the actual resolution will depend on the video source quality and client network conditions. It will enable incoming video if it is previously disabled.
Passing `null` resolution clears previously set preferences.
Optionally specify session ids of the participants this preference has effect on. Affects all participants by default.
`call.setIncomingVideoEnabled(false)`
Enables or disables incoming video from all remote call participants, and clears any preference for preferred resolution. …
=> feat(llc): manual quality selection

dogfooding/lib/screens/home_screen.dart, packages/stream_video/CHANGELOG.md, packages/stream_video_flutter/CHANGELOG.md, packages/stream_video_push_notification/.metadata, packages/stream_video_push_notification/CHANGELOG.md, packages/stream_video_push_notification/android/.gitignore, packages/stream_video_push_notification/android/build.gradle, packages/stream_video_push_notification/android/gradle/wrapper/gradle-wrapper.properties, packages/stream_video_push_notification/android/settings.gradle, packages/stream_video_push_notification/android/src/main/AndroidManifest.xml, packages/stream_video_push_notification/android/src/main/kotlin/io/getstream/video/flutter/stream_video_push_notification/StreamVideoPushNotificationPlugin.kt, packages/stream_video_push_notification/ios/Classes/StreamVideoPushNotificationPlugin.swift, packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart, packages/stream_video_push_notification/lib/stream_video_push_notification_method_channel.dart, packages/stream_video_push_notification/lib/stream_video_push_notification_platform_interface.dart, packages/stream_video_push_notification/pubspec.yaml
With the Android 14, the handling of full-screen notification permissions [has changed](https://source.android.com/docs/core/permissions/fsi-limits#:~:text=To%20prevent%20ad%20spam%20and,provide%20calling%20and%20alarm%20functionalities). To improve this within our SDK, we've introduced a `StreamVideoPushNotificationManager.ensureFullIntentPermission()` method. This method checks whether the necessary permission is granted. If the permission is not granted, it will direct the user to the settings page where they can enable it.
=> fix(Android): Added method to ensure lock screen permission on Android

.github/workflows/app-distribute.yml, dogfooding/android/app/build.gradle, dogfooding/android/app/src/debug/AndroidManifest.xml, dogfooding/android/app/src/main/AndroidManifest.xml, dogfooding/android/app/src/profile/AndroidManifest.xml, dogfooding/android/build.gradle, dogfooding/android/settings.gradle, dogfooding/pubspec.yaml, packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/coordinator/open_api/open_api_extensions.dart, packages/stream_video/pubspec.yaml, packages/stream_video_flutter/CHANGELOG.md, packages/stream_video_flutter/android/build.gradle, packages/stream_video_flutter/android/settings.gradle, packages/stream_video_flutter/android/src/main/AndroidManifest.xml, packages/stream_video_flutter/example/android/app/build.gradle, packages/stream_video_flutter/example/android/app/src/debug/AndroidManifest.xml, packages/stream_video_flutter/example/android/app/src/main/AndroidManifest.xml, packages/stream_video_flutter/example/android/app/src/profile/AndroidManifest.xml, packages/stream_video_flutter/lib/src/call_screen/lobby_view.dart, packages/stream_video_push_notification/CHANGELOG.md, packages/stream_video_push_notification/android/build.gradle, packages/stream_video_push_notification/android/settings.gradle, packages/stream_video_push_notification/android/src/main/AndroidManifest.xml, packages/stream_video_push_notification/pubspec.yaml
This pull request includes several updates to the Android build configurations and dependency versions across multiple files. The main changes involve migrating from the old `buildscript` and `apply plugin` syntax to the newer `plugins` block, as well as updating various dependencies to their latest versions.
* Migrated from `buildscript` and `apply plugin` to the `plugins` block in `dogfooding/android/app/build.gradle`, `packages/stream_video_flutter/android/build.gradle`, and `packages/stream_video_push_notification/android/build.gradle`. [[1]](diffhunk://#diff-2bdca7b22f85732560d4b82ccb49917660228cb55b19c7cf6f7cd260e8f0f9abR1-R7) [[2]](diffhunk://#diff-1c766d3332acba1026fde7a540d0ea0243cd378d90808774dafb4d46bc3ac73cL1-R3) [[3]](diffhunk://#diff-c5cb84595dd74b31e94c452a63bf5ab348c5575e7c …
=> chore: AGP 8 compatibility

packages/stream_video_flutter/CHANGELOG.md, packages/stream_video_flutter/android/build.gradle, packages/stream_video_flutter/android/src/main/kotlin/io/getstream/video/flutter/stream_video_flutter/service/PictureInPictureHelper.kt, packages/stream_video_flutter/lib/src/call_participants/call_participants.dart, packages/stream_video_flutter/lib/src/call_screen/call_content/call_content.dart
This pull request fixes the issues when ending the call while in Picture in Picture mode on Android. 
[`1`](diffhunk://#diff-d66727e797be3b1f71ebbf31fa6e48289f842aa4dacc106e1656a78a908ee39fL16-R20): Updated the `disablePictureInPicture` method to move the task to the back if the activity is in PiP mode.
[`2`](diffhunk://#diff-49f2b4ac60d9a3cd759f431e56e279e154389381085410130f697ee11027694bL151-R152): Added a check to ensure `_participants` is not empty before proceeding with the PiP layout mode.
[`3`](diffhunk://#diff-b5f5d4597cbc725270b58888c9f4b3dc1dae2958ab5490f014504ac0469fb29dR115-R120): Added logic to disable PiP mode when the call state status changes to disconnected.
=> fix(Android): fixes ending the call when in PiP

dogfooding/lib/app/app_content.dart, packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart, packages/stream_video/lib/src/push_notification/push_notification_manager.dart, packages/stream_video/lib/src/stream_video.dart, packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
Fixes the issue with accepting incoming call when another call is already active. Also fixes a dogfooding issue event subscriptions not being cleared properly when logging out.
=> fix: fix for accepting second call when already in a call

packages/stream_video/lib/src/call/sfu_stats_reporter.dart
The changes made on stream_video, specifically on the file sfu_stats_reporter.dart, avoid two unhandled exceptions on the web implementation of the package, due to methods from thermal and battery_plus that were being called on web and are not implemented in those platforms. The problem is best described on #836.
The fix was implemented by checking if the platform the code is running supports the methods that would be called, `isInBatterySaveMode()` and `getThermalStatus()`.
None.
The change can be tested by first running the package on web and verifying the error, before the PR, and running the same thing with the fixed code from this PR.
=> fix(stream_video): ensure thermal and battery_plus methods are only called on available platforms on sfu stats reporter

packages/stream_video_push_notification/ios/Classes/StreamVideoPKDelegateManager.swift, packages/stream_video_push_notification/ios/Classes/StreamVideoPushNotificationPlugin.swift
The app icon asset name was not passed correctly to the CallKit configuration when a VoIP push was received while the app was terminated.
=> fix(CallKit): fix for missing app icon in CallKit screen when app is terminated

packages/stream_video/pubspec.yaml, packages/stream_video_flutter/example/pubspec.yaml, packages/stream_video_flutter/pubspec.yaml, packages/stream_video_push_notification/pubspec.yaml
This pull request updates the `stream_webrtc_flutter` dependency across multiple files to ensure compatibility and take advantage of the latest improvements.
Dependency updates:
* [`packages/stream_video/pubspec.yaml`](diffhunk://#diff-48a465280a062b91a802680425bfc1431dd713332ad853d48b2972ac7278075fL33-R33): Updated `stream_webrtc_flutter` dependency from `^0.12.5+2` to `^0.12.8`.
* [`packages/stream_video_flutter/example/pubspec.yaml`](diffhunk://#diff-3af8756168dc6b6befd9081b79683a81589346dd2f0c11d510fdba4fe9375cd1L33-R33): Updated `stream_webrtc_flutter` dependency from `^0.12.5+2` to `^0.12.8`.
* [`packages/stream_video_flutter/pubspec.yaml`](diffhunk://#diff-580632d551a71a785c503628785be6c522ff1023f50c3261a1359aeec4daabf6L24-R24): Updated `stream_webrtc_flutter` dependency from …
=> chore: bumping webrtc dependency

dogfooding/lib/screens/call_screen.dart, dogfooding/lib/screens/home_screen.dart, dogfooding/lib/screens/login_screen.dart, dogfooding/lib/utils/consts.dart, packages/stream_video_flutter/CHANGELOG.md, packages/stream_video_flutter/lib/src/call_screen/lobby_video.dart
After making PR #845 I also wanted to make the app usable on wider displays. On multiple screens the layout breaks when you have a wide window.
On the home screen and the login screen I mainly made sure that the logo is not getting huge. I set the max width of that screen to 500px as the web implementation also doesn't get much wider than that. But we can discuss that value.
The lobby had the buttons weirdly aligned to the right, I added that to the max width that was already there.
The buttons on the call screen are very close to the bottom, so I added a bit of padding there.
| --- | --- |
| <img width="1728" alt="Screenshot 2025-02-06 at 16 35 15" …
=> chore(dogfooding) improve desktop layout

dogfooding/android/app/build.gradle, dogfooding/android/app/proguard-rules.pro, dogfooding/android/gradle.properties, dogfooding/android/gradle/wrapper/gradle-wrapper.properties, dogfooding/android/settings.gradle
The android dogfooding build doesn't compile anymore, because the record_android plugin doesn't work well with AGP 7. Upgrading to AGP 8 makes the app compile again and future proof.
This also contains a proguard file, because proguard behaves different on AGP 8.
No UI changes
Run the app on android, optionally with `flutter run --release`
=> chore(dogfooding): upgrade AGP to 8.8

.gitignore, melos.yaml
The `stream_webrtc_flutter` dependency was updated in the packages, but not in the melos.yaml file. Running melos bs would revert them.
`.gitignore` change is related to the flutter upgrade. See also https://github.com/flutter/flutter/issues/163220#issuecomment-2657214423
=> chore: Ignore cxx files and fix package version

dogfooding/lib/screens/login_screen.dart, dogfooding/macos/Runner.xcodeproj/project.pbxproj, dogfooding/macos/Runner/DebugProfile.entitlements, dogfooding/macos/Runner/Release.entitlements
Enable google signin on the macos dogfooding app
The Google signin plugin supports macos. To enable it we need to add the `keychain-access-groups` entitlement and enable development signing. See: https://pub.dev/packages/google_sign_in_ios#macos-setup
Run macos app and login with google
=> feat: enable google signin on macos

dogfooding/lib/app/app_content.dart, dogfooding/lib/screens/home_screen.dart, packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
When running the app on macOS it works, but it does throw a lot of exceptions. I want to prevent those exceptions.
Some things that are no longer done on macOS when you run the app:
`_tryConsumingIncomingCallFromTerminatedState`
`streamVideo.observeCoreCallKitEvents`
request permissions for notification, camera and microphone. Permission handler doesn't support those platforms.
Setup the StreamVideoPushNotificationManager.
It also enables the "IN-APP INCOMING SCREEN" for desktop and web.
No UI changes
Run macOS app with breakpoints enabled, before and after.
=> fix: prevent some actions impossible on desktop

.github/workflows/app-distribute.yml
Run workflow on push
I assumed `inputs.build_x` would be null or undefined, so that's why I checked for `!= false`, but apparently default is false for on push because here nothing runs: https://github.com/GetStream/stream-video-flutter/actions/runs/13544785120
So now I check if the event_name is 'push'.
=> fix: Always build both platforms on push event

dogfooding/lib/app/app_content.dart
Currently when you login on the web version of dogfooding it gives a grey/red screen. This fixes it.
After some debugging I found that pressing the login button (guest or email) calls `initPushNotificationManagerIfAvailable` which in turn handles deeplinks. For web the `initialUri` is not null, so it handles the deeplink and resets the AppInjector, which removes all existing dependencies.
As far as I know we don't need to handle deeplinks at all on web now.
No UI changes
Run a web build before and after.
=> fix: don't handle deeplink on login

packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/call/state/mixins/state_sfu_mixin.dart, packages/stream_video/lib/src/call_state.dart, packages/stream_video/lib/src/models/call_participant_state.dart, packages/stream_video/test/call_participant_state_sorting_test.dart
FLU-44
Add audioLevels and active speakers to match the swift sdk.
activeSpeakers is very similar to `otherParticipants` and `localParticipant`, so not fancy.
The list of audioLevels is maintained when doing `copyWith(audioLevel:...)`, so this level is added to the list every time the level changes.
I had to remove `const` to keep the API clean.
We can keep it const by adding a private field like this:
```dart
final List<double>? _audioLevels;
/// List of the last 10 audio levels.
List<double> get audioLevels => _audioLevels ?? [audioLevel];
```
But I don't think it's worth it.
No UI changes
=> feat: Add audioLevels and activeSpeakers

melos.yaml, packages/stream_video/pubspec.yaml, packages/stream_video_flutter/example/pubspec.yaml, packages/stream_video_flutter/pubspec.yaml, packages/stream_video_push_notification/pubspec.yaml
and downgrade dart_webrtc
New dart_webrtc has a bug for stats reporting. This version changes has a downgrade for dart_webrtc to make it work on web.
=> chore: bump webrtc version

dogfooding/lib/utils/consts.dart
We want to use pronto on web, but we currently only have demo available. We don't build web with multiple flavors.
On web always assume non-prod environment.
No UI changes
=> dogfooding: allow env switching on web

packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/call_events.dart, packages/stream_video/lib/src/call/permissions/permissions_manager.dart, packages/stream_video/lib/src/call/session/call_session.dart, packages/stream_video/lib/src/call/state/mixins/state_coordinator_mixin.dart, packages/stream_video/lib/src/call/state/mixins/state_participant_mixin.dart, packages/stream_video/lib/src/call/state/mixins/state_sfu_mixin.dart, packages/stream_video/lib/src/coordinator/coordinator_client.dart, packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart, packages/stream_video/lib/src/coordinator/retry/coordinator_client_retry.dart, packages/stream_video/lib/src/models/call_participant_pin.dart, packages/stream_video/lib/src/models/call_participant_state.dart, packages/stream_video/lib/src/sfu/data/events/sfu_event_mapper_extensions.dart, packages/stream_video/lib/src/sfu/data/events/sfu_events.dart, packages/stream_video/lib/src/sfu/data/models/sfu_call_state.dart, packages/stream_video/lib/src/sfu/data/models/sfu_pin.dart, packages/stream_video/lib/src/sorting/call_participant_state_sorting.dart, packages/stream_video/test/call_participant_state_sorting_test.dart
FLU-66
Added `setParticipantPinnedForEveryone()` method to `Call` object that allows for pinning given session to the top of the list for everyone in the call. It requires user to have `pin-for-everyone` permission set in the Dashboard. 
The `setParticipantPinned()` method is still available and as before will only pin the session locally.
=> feat: Added pin/unpin for everyone method to Call

packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/permissions/permissions_manager.dart, packages/stream_video/lib/src/call/state/mixins/state_call_actions_mixin.dart, packages/stream_video/lib/src/coordinator/coordinator_client.dart, packages/stream_video/lib/src/coordinator/open_api/coordinator_client_open_api.dart, packages/stream_video/lib/src/coordinator/retry/coordinator_client_retry.dart, packages/stream_video_flutter/CHANGELOG.md
Added `membersLimit` parameter to `getOrCreate()` and `join()` that was missing previously. Connected to added doc page: https://github.com/GetStream/docs-content/pull/221
=> chore(llc): added membersLimit parameter

dogfooding/pubspec.yaml, melos.yaml, packages/stream_video/CHANGELOG.md, packages/stream_video/pubspec.yaml, packages/stream_video_flutter/CHANGELOG.md, packages/stream_video_flutter/example/pubspec.yaml, packages/stream_video_flutter/pubspec.yaml, packages/stream_video_push_notification/pubspec.yaml
Currently we are incompatible with chat 9.5 because of the outdated dependency on device_info_plus. This makes it compatible again.
=> fix: Update device_info and webrtc dependencies

packages/stream_video/lib/src/call/call.dart
This PR fixes #905.
It does so by listening to the mediaTrack onEnded event and disabling the screen sharing.
It can be tested through https://getstream.github.io/stream-video-flutter/ (where it doesn't work on the current version) and then testing with the modifications on this branch on web version.
=> fix(web): ensure screen sharing is ended when stopping it through browser

packages/stream_video_flutter/android/src/main/AndroidManifest.xml
This PR aims to avoid errors on manufacturers that enforce the MANAGE_OWN_CALLS permission when using a foreground service of type phoneCall. It fixes #907 .
The MANAGE_OWN_CALLS permission was added on the AndroidManifest of stream_video_flutter package.
We were able to reproduce the issue on a Samsung device, but I'm not sure it's on all Samsung devices. The permission is a prerequisite from Android, as explained on #907.
=> fix(android): add missing MANAGE_OWN_CALLS permission due to foreground service with phoneCall type

packages/stream_video_flutter/lib/src/renderer/video_renderer.dart
FLU-73
There was a race between `VideoRenderer` and `SfuTrackPublishedEvent` event handling. When `VideoRenderer` was rendered before publishedTrack was created and added for the participant, it wouldn't be subscribed until `VideoRenderer` visibility changed again. 
This PR changes `VideoRenderer` to `StatefulWidget` and invokes `onVisibilityChanged` if the widget configuration changes with a late published track added to the participants' tracks array.
=> fix: subscribe to remote track when it comes late

packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/session/call_session.dart, packages/stream_video/lib/src/call/state/mixins/state_call_actions_mixin.dart, packages/stream_video/lib/src/call/state/mixins/state_lifecycle_mixin.dart, packages/stream_video/lib/src/call/state/mixins/state_sfu_mixin.dart, packages/stream_video/lib/src/sfu/sfu_extensions.dart
This pull request addresses a problem that occurs when a participant joins a call from multiple devices, leading to several issues with call controls. The fix ensures that we compare both the userId and sessionId, rather than just the userId, allowing us to differentiate between the same user participating in different sessions.
Fixes: https://github.com/GetStream/stream-video-flutter/issues/914
FLU-45
=> fix(llc): fix checks for local participant

packages/stream_video/lib/src/webrtc/rtc_manager.dart
With the changes in how we handle RTC transceivers during codec negotiation implementation, we no longer need to unpublish the previous screen sharing track when we start screen sharing with new constraints. The transceiver will be reused for the new track.
=> fix(llc): multiple screen sharing sources

dogfooding/lib/screens/call_screen.dart, packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/state/call_state_notifier.dart, packages/stream_video/lib/src/call/state/mixins/state_sfu_mixin.dart, packages/stream_video/lib/src/call_state.dart, packages/stream_video/lib/src/stream_video.dart
Fixes FLU-47
This pull request addresses the management of call preferences, particularly during the ringing flow. Previously, call preferences set while creating a ringing call could be overlooked if `StreamVideo.incomingCall` was set beforehand when handling the ringing event. Additionally, default call properties have been added to the StreamVideo options for improved functionality.
=> fix: call preference initialization during ringing

packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/push_notification/push_notification_manager.dart, packages/stream_video_flutter/lib/src/call_screen/call_container.dart, packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart
Resolves FLU-83
This PR makes sure that muting the call on the CallKit screen on iOS is synced with the mute in SDK in both directions
=> feat: sync CallKit screen mute button with SDK mute action

packages/stream_video_push_notification/lib/src/stream_video_push_notification.dart, packages/stream_video_push_notification/lib/src/stream_video_push_params.dart, packages/stream_video_push_notification/lib/src/stream_video_push_params.g.dart, packages/stream_video_push_notification/pubspec.yaml
fixes FLU-95
Bumps the `flutter_callkit_incoming` version to the latest release and disables the new outgoing call notification, which is enabled by default, since we have a similar feature on our end.
=> chore: bump flutter callkit incoming

packages/stream_video/lib/src/types/other.dart, packages/stream_video/test/src/types/rtc_configuration_test.dart
Fixes FLU-91
RTP BUNDLE is a mechanism in [RTP](https://bloggeek.me/webrtcglossary/rtp/) that enables using a single socket/connection to send multiple media types.
This is typically used to send audio and video over the same connection, and allows reducing the number of opened sockets and pinholes that need to be managed and reduces the resources required to get a session work through a firewall or [NAT](https://bloggeek.me/webrtcglossary/nat/) device.
Sets the `bundlePolicy` and includes a unit test
No UI change
Added a test to verify the field is set. We should do some manual call tests
=> feat: Set bundlePolicy for the peerconnection

packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/state/mixins/state_coordinator_mixin.dart, packages/stream_video/lib/src/call/state/mixins/state_lifecycle_mixin.dart, packages/stream_video/lib/src/call_state.dart, packages/stream_video/lib/src/coordinator/open_api/open_api_mapper_extensions.dart, packages/stream_video/lib/src/models/call_member_state.dart, packages/stream_video_flutter/lib/src/call_screen/incoming_call/incoming_call_content.dart, packages/stream_video_flutter/lib/src/call_screen/outgoing_call/outgoing_call_content.dart
This PR adds `callMembers` to `CallState` and uses it in ringing cases instead of participants. It also removes the logic of creating participants from members since it's no longer needed.
=> chore: added members to call state

dogfooding/ios/Podfile, dogfooding/ios/Runner.xcodeproj/project.pbxproj, packages/stream_video_flutter/ios/stream_video_flutter.podspec, packages/stream_video_noise_cancellation/ios/stream_video_noise_cancellation.podspec, packages/stream_video_push_notification/ios/stream_video_push_notification.podspec, packages/stream_video_screen_sharing/ios/stream_video_screen_sharing.podspec
We set minimum iOS version to 16, because we had some build issues, but now it's working again on iOS 14. So we have a broader device set we allow.
I tested if it runs on an iPhone X simulator with iOS 15.5, about the lowest I could install.
=> chore: putting minimum iOS version back to 14

packages/stream_video_flutter/lib/src/livestream/livestream_player.dart
When a user leaves the livestream it should no longer be a participant of the call
When leaving the widget we now also leave the actual call.
No relevant changes
I tested it with the live stream tutorial. First the counter did not go down when somebody left the livestream, now the viewing counter does go down.
=> fix: leave call when leaving livestream

dogfooding/pubspec.yaml, packages/stream_video/pubspec.yaml, pubspec.lock
Latest version of `internet_connection_checker_plus` fixes some issues with urls used to check connection
=> chore: bump internet connection checker dependency

packages/stream_video_flutter/lib/src/call_participants/call_participants.dart
Fixes FLU-82
Prevent jumping around of participant locations
Some sorting rules are not applied when participants are visible. However, because we weren't storing the result of the previous sort participants were jumping back to their previous position. By keeping the sort result and applying that to the new set of participants we make sure participants only jump around when we want them to.
You can start a call with many participants and try to play with who's talking or screen sharing for example.
=> Store previous sorting of participants before sorting again

dogfooding/lib/app/app.dart, dogfooding/lib/app/app_content.dart
We had an artificial delay when initializing the app (to show the splash screen longer) that interfered with CallKit integration. When the app was started from a terminated state after a VoIP push was received (iOS), quickly accepting the call would not work because CallKit events were not observed.
=> fix: fix app init delay

dogfooding/lib/widgets/call_duration_title.dart, packages/stream_video/CHANGELOG.md, packages/stream_video/lib/src/call/call.dart, packages/stream_video/lib/src/call/session/call_session.dart, packages/stream_video/lib/src/call/state/call_state_notifier.dart, packages/stream_video/lib/src/call/state/mixins/state_lifecycle_mixin.dart, packages/stream_video/lib/src/call_state.dart, packages/stream_video/lib/src/models/call_metadata.dart, packages/stream_video_flutter/lib/src/livestream/livestream_player.dart
resolves FLU-136
We aim to simplify the process for integrators to obtain the current call duration by providing them with a stream of the duration in seconds.
Added a Stream<int> in `CallStateNotifier` that is started whenever `startedAt` or `liveStartedAt` is set. The stream is exposed in `Call` as `callDurationSecondsStream`. 
The new stream is now also used in Dogfooding timer widget and `LivestreamPlayer` widget.
=> chore: call duration stream

packages/stream_video_flutter/lib/src/call_participants/screen_share_call_participants_content.dart, packages/stream_video_flutter/lib/src/renderer/video_renderer.dart
resolves FLU-131
This PR addresses an issue with our track visibility logic. We currently unsubscribe from video tracks when their visibility falls below 30% to conserve resources. However, this had an unintended side effect: when users zoom in on a screen share track using InteractiveViewer, the zoom could reduce the track's visible area below the threshold, causing it to be unsubscribed.
This fix ensures that the screen share track remains subscribed even when zoomed in, preserving the user experience during screen sharing.
=> fix: do not unsubscribe screen share track when zooming

dogfooding/lib/widgets/closed_captions_widget.dart, packages/stream_video_flutter/lib/src/call_participants/screen_share_call_participants_content.dart
Fixes FLU-114
Make the default video widgets work better when you have a wide, but not so high window.
This switches the layout of screen share view automatically to having participants on the right if your complete window is wider than 16/9. The 16/9 is the ratio of screen share view.
I also made the captions bar less high with options to get it back to the original values.
First screenshot focusses on the height of the caption bar, the second one also shows the change of screen sharing.
| --- | --- |
| <img width="1929" alt="captions_before" src="https://github.com/user-attachments/assets/1bedc014-f5aa-4e75-b411-ed395e227338" /> | <img width="1988" alt="captions_after" src="https://github.com/user-attachments/assets/493d87e3-9a19-4abb-a167-ae3c1f5cec36" /> |
| <img …
=> Improve horizontal layout on very wide windows

.github/workflows/app-distribute.yml, dogfooding/android/fastlane/Fastfile, dogfooding/ios/fastlane/Fastfile
Make app distribution for dogfooding easier
Depending on the flavor this either pushes to public beta testers or internal.
Previously production releases had to be made manually, now they are (or should be) made when you publish a new release.
Android test run: https://github.com/GetStream/stream-video-flutter/actions/runs/15185467581
iOS test run: https://github.com/GetStream/stream-video-flutter/actions/runs/15186409991
=> chore: improve app distribution for dev and prod
